<div class="container">
    <h1>
        Edit Post
    </h1>

    <form action="" method='post' enctype="multipart/form-data">
        <p>
            <label>
                Description
            </label>
            <?php echo $form->render('title',[
                'maxlength'   => 30,
                'placeholder' => 'Title',
                'class' => 'form-control'
            ]); ?>
        </p>
    </form>
</div>
